# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_NewFileTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 40)
        Dialog.setMinimumSize(QtCore.QSize(517, 40))
        Dialog.setMaximumSize(QtCore.QSize(517, 40))
        self.pushButton_define = QtWidgets.QPushButton(Dialog)
        self.pushButton_define.setGeometry(QtCore.QRect(270, 10, 61, 23))
        self.pushButton_define.setObjectName("pushButton_define")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 10, 81, 22))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(120, 10, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_add = QtWidgets.QPushButton(Dialog)
        self.pushButton_add.setGeometry(QtCore.QRect(350, 10, 31, 23))
        self.pushButton_add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/button_add.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_del = QtWidgets.QPushButton(Dialog)
        self.pushButton_del.setGeometry(QtCore.QRect(390, 10, 31, 23))
        self.pushButton_del.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/button_del.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_del.setIcon(icon1)
        self.pushButton_del.setObjectName("pushButton_del")
        self.pushButton_run = QtWidgets.QPushButton(Dialog)
        self.pushButton_run.setGeometry(QtCore.QRect(430, 10, 31, 23))
        self.pushButton_run.setObjectName("pushButton_run")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(470, 10, 41, 23))
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_define.setToolTip(_translate("Dialog", "Set default header"))
        self.pushButton_define.setText(_translate("Dialog", "Define"))
        self.label.setText(_translate("Dialog", "Set Default: "))
        self.pushButton_add.setToolTip(_translate("Dialog", "Add a column to the last"))
        self.pushButton_del.setToolTip(_translate("Dialog", "Delete the last column"))
        self.pushButton_run.setToolTip(_translate("Dialog", "Create a smp file"))
        self.pushButton_run.setText(_translate("Dialog", "Run"))
        self.pushButton_close.setToolTip(_translate("Dialog", "Create a smp file"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
